// apps/back/src/app/api/scores/route.ts
//
// Internal scores API. In production this is where the expensive third-party
// scores provider is called. For this POC it returns deterministic, time-derived
// mock data so engineers can clearly see values change over time as the data
// flows: back -> front ISR cache -> RSC payload -> reconciled DOM.
//
// Auth is enforced at the Vercel edge by a Firewall rule that blocks any request
// whose `x-api-secret` header does not match BACK_API_SECRET. This function only
// executes for callers that already passed that check — see vercel.json.

export const dynamic = "force-dynamic";

export interface Score {
  gameId: string;
  home: string;
  away: string;
  homeScore: number;
  awayScore: number;
  status: "scheduled" | "live" | "halftime" | "final";
  // POC-only fields, so engineers can visually confirm freshness/propagation.
  // These won't exist in the production shape but make the data flow obvious.
  clock: string; // mm:ss game clock derived from elapsed time
  updatedAt: string; // ISO timestamp this payload was generated by `back`
}

const GAMES = [
  { gameId: "g1", home: "Wallabies", away: "All Blacks" },
  { gameId: "g2", home: "Springboks", away: "England" },
  { gameId: "g3", home: "Ireland", away: "France" },
  { gameId: "g4", home: "Argentina", away: "Wales" },
] as const;

const GAME_LENGTH_SECONDS = 80 * 60; // a notional 80-minute match

function formatClock(totalSeconds: number): string {
  const mm = Math.floor(totalSeconds / 60)
    .toString()
    .padStart(2, "0");
  const ss = Math.floor(totalSeconds % 60)
    .toString()
    .padStart(2, "0");
  return `${mm}:${ss}`;
}

// Deterministic, stateless mock generator. Every instance/region computes the
// same values for the same instant, which is exactly what we want behind ISR.
function fetchFromThirdPartyAPI(now: Date): Score[] {
  const epochSeconds = Math.floor(now.getTime() / 1000);
  const elapsed = epochSeconds % GAME_LENGTH_SECONDS;
  const updatedAt = now.toISOString();

  return GAMES.map((game, i) => {
    // Stagger each game so the board has variety. Scores tick up roughly every
    // ~90s of game time, which at 5s polling is visible within a minute or two.
    const seed = elapsed + i * 137;
    const homeScore = Math.floor(seed / 90) % 60;
    const awayScore = Math.floor((seed + 45) / 90) % 60;

    let status: Score["status"];
    if (elapsed < 5) status = "scheduled";
    else if (Math.abs(elapsed - GAME_LENGTH_SECONDS / 2) < 5)
      status = "halftime";
    else if (elapsed >= GAME_LENGTH_SECONDS - 5) status = "final";
    else status = "live";

    return {
      gameId: game.gameId,
      home: game.home,
      away: game.away,
      homeScore,
      awayScore,
      status,
      clock: formatClock(elapsed),
      updatedAt,
    };
  });
}

export async function GET() {
  // The Vercel Firewall has already rejected unauthorized requests at the edge,
  // so reaching this point means the caller presented a valid x-api-secret.
  const scores = fetchFromThirdPartyAPI(new Date());
  return Response.json(scores);
}
